version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - courier-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: trackingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - courier-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - tracking-service
      - store-service
    environment:
      GATEWAY_TRACKING-SERVICE_URI: http://tracking-service:8081
    networks:
      - courier-net

  tracking-service:
    build:
      context: ./tracking-service
    container_name: tracking-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trackingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      STORE_SERVICE_URL: http://store-service:8082
    networks:
      - courier-net

  store-service:
    build:
      context: ./store-service
    container_name: store-service
    ports:
      - "8082:8082"
    networks:
      - courier-net

networks:
  courier-net:
    driver: bridge
